### ISSUE TITLE
Identity

### ISSUE THREAD

**Issue by m-rk** [SaxJ/sound-room-client#15]
**Is your feature request related to a problem? Please describe.**
Provide an analog to real life and prevent a fart-a-thon by identifying who makes each sound

**Describe the solution you'd like**
Google Auth, as a per-room toggled requirement so it isn't imposed universally but can be imposed on a room

**Describe alternatives you've considered**
Maybe a simple input for a pseudonym/nick

**Comment by SaxJ** [comment]
Universal Google auth implemented. Persistent rooms with configurable settings will be a future separate task.
