### ISSUE TITLE
Rooms

### ISSUE THREAD

**Issue by m-rk** [SaxJ/sound-room-client#2]
**Is your feature request related to a problem? Please describe.**
I can't separate sounds from one session to another, so having a connection means being able to send and receive sounds to/from every single user forever

**Describe the solution you'd like**
Unique sessions that are unlisted but can be shared (e.g. unique URLs)

**Describe alternatives you've considered**
Warning any user that they will be interacting with all other users

**Comment by SaxJ** [comment]
Good idea. I've implemented a first pass at "rooms", and it should be easy to follow up with adding that to the URL.
